FactoryBot.define do
  factory :create_score_subject_average do
    title { '予備校模試' }
    jpn_ctp { 100 }
    jpn_classic { 100 }
    jpn_chinese { 100 }
    jpn { 200 }
    math_1_a { 100 } 
    math_2_b { 100 }
    math_3_c { 100 }
    math_1 { 100 }
    math_2 { 100 }
    math_3 { 100 }
    math_a { 100 }
    math_b { 100 }
    math_c { 100 }
    math { 100 }
    book_keep { 100 } 
    basic_info { 100 }
    science_n_life { 100 }
    basic_physics { 100 }
    physics { 100 }
    basic_chemistry { 100 } 
    chemistry { 100 }
    basic_earth_science { 100 } 
    earth_science { 100 }
    basic_biology { 100 }
    biology { 100 }
    science { 100 }
    wld_history_a { 100 } 
    wld_history_b { 100 }
    dms_history_a { 100 }
    dms_history_b { 100 }
    geography_a { 100 }
    geography_b { 100 }
    ctp_society { 100 }
    ethics { 100 }
    politics_n_economy { 100 }
    ethics_n_politics_n_economy { 100 }
    society { 100 }
    listening { 100 }
    reading { 100 }
    english { 200 }
    language { 100 }
    review { "難しかったがなんとか平均点を超えられた。次回も頑張ろう。" }
    avg_jpn_ctp { 100 } 
    avg_jpn_classic { 100 } 
    avg_jpn_chinese { 100 }
    avg_jpn { 200 }
    avg_math_1_a { 100 }
    avg_math_2_b { 100 }
    avg_math_3_c { 100 }
    avg_math_1 { 100 }
    avg_math_2 { 100 }
    avg_math_3 { 100 }
    avg_math_a { 100 }
    avg_math_b { 100 }
    avg_math_c { 100 }
    avg_math { 100 }
    avg_book_keep { 100 }
    avg_basic_info { 100 }
    avg_science_n_life { 100 }
    avg_basic_physics { 100 }
    avg_physics { 100 }
    avg_basic_chemistry { 100 }
    avg_chemistry { 100 }
    avg_basic_earth_science { 100 }
    avg_earth_science { 100 }
    avg_basic_biology { 100 }
    avg_biology { 100 }
    avg_science { 100 }
    avg_wld_history_a { 100 }
    avg_wld_history_b { 100 }
    avg_dms_history_a { 100 }
    avg_dms_history_b { 100 }
    avg_geography_a { 100 }
    avg_geography_b { 100 }
    avg_ctp_society { 100 }
    avg_ethics { 100 }
    avg_politics_n_economy { 100 } 
    avg_ethics_n_politics_n_economy { 100 }
    avg_society { 100 }
    avg_listening { 100 }
    avg_reading { 100 }
    avg_english { 200 }
    avg_language { 100 }
    sub_jpn_ctp { '現代文' }
    sub_jpn_classic { '古文' }
    sub_jpn_chinese { '漢文' }
    sub_jpn { '国語' }
    sub_math_1_a { '数学ⅠA' }
    sub_math_2_b { '数学ⅡB' }
    sub_math_3_c { '数学ⅢC' }
    sub_math_1 { '数学Ⅰ' }
    sub_math_2 { '数学Ⅱ' }
    sub_math_3 { '数学Ⅲ' }
    sub_math_a { '数学A' }
    sub_math_b { '数学B' }
    sub_math_c { '数学C' }
    sub_math { '数学' }
    sub_book_keep { '簿記・会計' }
    sub_basic_info { '情報関係基礎' }
    sub_science_n_life { '科学と人間生活' }
    sub_basic_physics { '物理基礎' }
    sub_physics { '物理' }
    sub_basic_chemistry { '化学基礎' }
    sub_chemistry { '化学' }
    sub_basic_earth_science { '地学基礎' }
    sub_earth_science { '地学' }
    sub_basic_biology { '生物基礎' }
    sub_biology { '生物' }
    sub_science { '理科' }
    sub_wld_history_a { '世界史A' }
    sub_wld_history_b { '世界史B' }
    sub_dms_history_a { '日本史A' }
    sub_dms_history_b { '日本史B' }
    sub_geography_a { '地理A' }
    sub_geography_b { '地理B' }
    sub_ctp_society { '現代社会' }
    sub_ethics { '倫理' }
    sub_politics_n_economy { '政治・経済' }
    sub_ethics_n_politics_n_economy { '倫理・政治・経済' }
    sub_society { '社会' }
    sub_listening { 'リスニング' }
    sub_reading { 'リーディング' }
    sub_english { '英語' }
    sub_language { '外国語' }
    user_id { 1 }
    score_id { 2 }
    tag_name { 'ABC予備校模試' }
  end
end
